# generated by datamodel-codegen:
#   filename:  codex.schema.json
#   timestamp: 2026-05-11T08:24:47+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AbsolutePathBuf(RootModel[str]):
    root: str = Field(
        ...,
        description="A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem).\n\nIMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.",
    )


class AgentRoleToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    config_file: AbsolutePathBuf | None = Field(
        None,
        description="Path to a role-specific config layer. Relative paths are resolved relative to the `config.toml` that defines them.",
    )
    description: str | None = Field(
        None,
        description="Human-facing role documentation used in spawn tool guidance. Required unless supplied by the referenced agent role file.",
    )
    nickname_candidates: list[str] | None = Field(
        None, description="Candidate nicknames for agents spawned with this role."
    )


class AgentsToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    interrupt_message: bool | None = Field(
        None,
        description="Whether to record a model-visible message when an agent turn is interrupted. Defaults to true.",
    )
    job_max_runtime_seconds: int | None = Field(
        None,
        description="Default maximum runtime in seconds for agent job workers.",
        ge=1,
    )
    max_depth: int | None = Field(
        None,
        description="Maximum nesting depth allowed for spawned agent threads. Root sessions start at depth 0.",
        ge=1,
    )
    max_threads: int | None = Field(
        None,
        description="Maximum number of agent threads that can be open concurrently. When unset, no limit is enforced.",
        ge=1,
    )


class AltScreenMode1(StrEnum):
    """
    Auto-detect: disable alternate screen in Zellij, enable elsewhere.
    """

    auto = "auto"


class AltScreenMode2(StrEnum):
    """
    Always use alternate screen (original behavior).
    """

    always = "always"


class AltScreenMode3(StrEnum):
    """
    Never use alternate screen (inline mode only).
    """

    never = "never"


class AltScreenMode(RootModel[AltScreenMode1 | AltScreenMode2 | AltScreenMode3]):
    root: AltScreenMode1 | AltScreenMode2 | AltScreenMode3 = Field(
        ...,
        description="Controls whether the TUI uses the terminal's alternate screen buffer.\n\n**Background:** The alternate screen buffer provides a cleaner fullscreen experience without polluting the terminal's scrollback history. However, it conflicts with terminal multiplexers like Zellij that strictly follow the xterm specification, which defines that alternate screen buffers should not have scrollback.\n\n**Zellij's behavior:** Zellij intentionally disables scrollback in alternate screen mode (see https://github.com/zellij-org/zellij/pull/1032) to comply with the xterm spec. This is by design and not configurable in Zellij—there is no option to enable scrollback in alternate screen mode.\n\n**Solution:** This setting provides a pragmatic workaround: - `auto` (default): Automatically detect the terminal multiplexer. If running in Zellij, disable alternate screen to preserve scrollback. Enable it everywhere else. - `always`: Always use alternate screen mode (original behavior before this fix). - `never`: Never use alternate screen mode. Runs in inline mode, preserving scrollback in all multiplexers.\n\nThe CLI flag `--no-alt-screen` can override this setting at runtime.",
    )


class AnalyticsConfigToml(BaseModel):
    """
    Analytics settings loaded from config.toml. Fields are optional so we can apply defaults.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = Field(
        None,
        description="When `false`, disables analytics across Codex product surfaces in this profile.",
    )


class AppToolApproval(StrEnum):
    auto = "auto"
    prompt = "prompt"
    approve = "approve"


class AppToolConfig(BaseModel):
    """
    Per-tool settings for a single app tool.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    approval_mode: AppToolApproval | None = Field(None, description="Approval mode for this tool.")
    enabled: bool | None = Field(
        None,
        description="Whether this tool is enabled. `Some(true)` explicitly allows this tool.",
    )


class AppToolsConfig(RootModel[dict[str, AppToolConfig]]):
    """
    Tool settings for a single app.
    """

    root: dict[str, AppToolConfig]


class ApprovalsReviewer(StrEnum):
    """
    Configures who approval requests are routed to for review. Examples include sandbox escapes, blocked network access, MCP approval prompts, and ARC escalations. Defaults to `user`. `auto_review` uses a carefully prompted subagent to gather relevant context and apply a risk-based decision framework before approving or denying the request. The legacy value `guardian_subagent` is accepted for compatibility.
    """

    user = "user"
    auto_review = "auto_review"
    guardian_subagent = "guardian_subagent"


class AppsDefaultConfig(BaseModel):
    """
    Default settings that apply to all apps.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    destructive_enabled: bool | None = Field(
        None,
        description="Whether tools with `destructive_hint = true` are allowed by default.",
    )
    enabled: bool | None = Field(
        True,
        description="When `false`, apps are disabled unless overridden by per-app settings.",
    )
    open_world_enabled: bool | None = Field(
        None,
        description="Whether tools with `open_world_hint = true` are allowed by default.",
    )


class AppsMcpPathOverrideConfigToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = None
    path: str | None = None


class AskForApproval1(StrEnum):
    """
    Under this policy, only "known safe" commands—as determined by `is_safe_command()`—that **only read files** are auto‑approved. Everything else will ask the user to approve.
    """

    untrusted = "untrusted"


class AskForApproval2(StrEnum):
    """
    DEPRECATED: *All* commands are auto‑approved, but they are expected to run inside a sandbox where network access is disabled and writes are confined to a specific set of paths. If the command fails, it will be escalated to the user to approve execution without a sandbox. Prefer `OnRequest` for interactive runs or `Never` for non-interactive runs.
    """

    on_failure = "on-failure"


class AskForApproval3(StrEnum):
    """
    The model decides when to ask the user for approval.
    """

    on_request = "on-request"


class AskForApproval5(StrEnum):
    """
    Never ask the user to approve commands. Failures are immediately returned to the model, and never escalated to the user for approval.
    """

    never = "never"


class AuthCredentialsStoreMode1(StrEnum):
    """
    Persist credentials in CODEX_HOME/auth.json.
    """

    file = "file"


class AuthCredentialsStoreMode2(StrEnum):
    """
    Persist credentials in the keyring. Fail if unavailable.
    """

    keyring = "keyring"


class AuthCredentialsStoreMode3(StrEnum):
    """
    Use keyring when available; otherwise, fall back to a file in CODEX_HOME.
    """

    auto = "auto"


class AuthCredentialsStoreMode4(StrEnum):
    """
    Store credentials in memory only for the current process.
    """

    ephemeral = "ephemeral"


class AuthCredentialsStoreMode(
    RootModel[
        AuthCredentialsStoreMode1
        | AuthCredentialsStoreMode2
        | AuthCredentialsStoreMode3
        | AuthCredentialsStoreMode4
    ]
):
    root: (
        AuthCredentialsStoreMode1
        | AuthCredentialsStoreMode2
        | AuthCredentialsStoreMode3
        | AuthCredentialsStoreMode4
    ) = Field(..., description="Determine where Codex should store CLI auth credentials.")


class AutoReviewToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    policy: str | None = Field(
        None,
        description="Additional policy instructions inserted into the guardian prompt.",
    )


class BundledSkillsConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True


class DebugConfigLockToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    allow_codex_version_mismatch: bool | None = Field(
        None,
        description="Allow replaying a lock generated by a different Codex version.",
    )
    export_dir: AbsolutePathBuf | None = Field(
        None,
        description="Directory where Codex writes effective session config lock files.",
    )
    load_path: AbsolutePathBuf | None = Field(
        None, description="Lockfile to replay as the authoritative effective config."
    )
    save_fields_resolved_from_model_catalog: bool | None = Field(
        None,
        description="Save fields resolved from the model catalog/session configuration.",
    )


class DebugToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    config_lockfile: DebugConfigLockToml | None = None


class ExternalConfigMigrationPrompts(BaseModel):
    """
    Settings for notices we display to users via the tui and app-server clients (primarily the Codex IDE extension). NOTE: these are different from notifications - notices are warnings, NUX screens, acknowledgements, etc.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    home: bool | None = Field(
        None,
        description="Tracks whether home-level external config migration prompts are hidden.",
    )
    home_last_prompted_at: int | None = Field(
        None,
        description="Tracks the last time the home-level external config migration prompt was shown.",
    )
    project_last_prompted_at: dict[str, int] | None = Field(
        {},
        description="Tracks the last time a project-level external config migration prompt was shown.",
    )
    projects: dict[str, bool] | None = Field(
        {},
        description="Tracks which project paths have opted out of external config migration prompts.",
    )


class FeatureTomlForAppsMcpPathOverrideConfigToml(RootModel[bool | AppsMcpPathOverrideConfigToml]):
    root: bool | AppsMcpPathOverrideConfigToml


class FeedbackConfigToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = Field(
        None,
        description="When `false`, disables the feedback flow across Codex product surfaces.",
    )


class FileSystemAccessMode(StrEnum):
    """
    Access mode for a filesystem entry.

    When two equally specific entries target the same path, we compare these by conflict precedence rather than by capability breadth: `none` beats `write`, and `write` beats `read`.
    """

    read = "read"
    write = "write"
    none = "none"


class FilesystemPermissionToml(RootModel[FileSystemAccessMode | dict[str, FileSystemAccessMode]]):
    root: FileSystemAccessMode | dict[str, FileSystemAccessMode]


class FilesystemPermissionsToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    glob_scan_max_depth: int | None = Field(
        None,
        description="Optional maximum depth for expanding unreadable glob patterns on platforms that snapshot glob matches before sandbox startup.",
        ge=1,
    )


class ForcedLoginMethod(StrEnum):
    chatgpt = "chatgpt"
    api = "api"


class GhostSnapshotToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    disable_warnings: bool | None = Field(
        None, description="Legacy no-op setting retained for compatibility."
    )
    ignore_large_untracked_dirs: int | None = Field(
        None, description="Legacy no-op setting retained for compatibility."
    )
    ignore_large_untracked_files: int | None = Field(
        None, description="Legacy no-op setting retained for compatibility."
    )


class GranularApprovalConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mcp_elicitations: bool = Field(..., description="Whether to allow MCP elicitation prompts.")
    request_permissions: bool | None = Field(
        False,
        description="Whether to allow prompts triggered by the `request_permissions` tool.",
    )
    rules: bool = Field(
        ...,
        description="Whether to allow prompts triggered by execpolicy `prompt` rules.",
    )
    sandbox_approval: bool = Field(
        ...,
        description="Whether to allow shell command approval requests, including inline `with_additional_permissions` and `require_escalated` requests.",
    )
    skill_approval: bool | None = Field(
        False,
        description="Whether to allow approval prompts triggered by skill script execution.",
    )


class HistoryPersistence1(StrEnum):
    """
    Save all history entries to disk.
    """

    save_all = "save-all"


class HistoryPersistence2(StrEnum):
    """
    Do not write history to disk.
    """

    none = "none"


class HistoryPersistence(RootModel[HistoryPersistence1 | HistoryPersistence2]):
    root: HistoryPersistence1 | HistoryPersistence2


class Type(StrEnum):
    command = "command"


class HookHandlerConfig1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    async_: bool | None = Field(False, alias="async")
    command: str
    status_message: str | None = Field(None, alias="statusMessage")
    timeout: int | None = Field(None, ge=0)
    type: Type


class Type1(StrEnum):
    prompt = "prompt"


class HookHandlerConfig2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Type1


class Type2(StrEnum):
    agent = "agent"


class HookHandlerConfig3(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Type2


class HookHandlerConfig(RootModel[HookHandlerConfig1 | HookHandlerConfig2 | HookHandlerConfig3]):
    root: HookHandlerConfig1 | HookHandlerConfig2 | HookHandlerConfig3


class HookStateToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = None
    trusted_hash: str | None = None


class KeybindingsSpec(RootModel[str | list[str]]):
    root: str | list[str] = Field(
        ...,
        description='One action binding value in config.\n\nThis accepts either:\n\n1. A single key spec string (`"ctrl-a"`). 2. A list of key spec strings (`["ctrl-a", "alt-a"]`).\n\nAn empty list explicitly unbinds the action in that scope. Because an explicit empty list is still a configured value, runtime resolution must not fall through to global or built-in defaults for that action.',
    )


class MarketplaceSourceType(StrEnum):
    git = "git"
    local = "local"


class MatcherGroup(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    hooks: list[HookHandlerConfig] | None = Field([], validate_default=True)
    matcher: str | None = None


class McpServerEnvVar1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    source: str | None = None


class McpServerEnvVar(RootModel[str | McpServerEnvVar1]):
    root: str | McpServerEnvVar1


class McpServerToolConfig(BaseModel):
    """
    Per-tool approval settings for a single MCP server tool.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    approval_mode: AppToolApproval | None = Field(None, description="Approval mode for this tool.")


class MemoriesToml(BaseModel):
    """
    Memories settings loaded from config.toml.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    consolidation_model: str | None = Field(
        None, description="Model used for memory consolidation."
    )
    disable_on_external_context: bool | None = Field(
        None,
        description='When `true`, external context sources mark the thread `memory_mode` as `"polluted"`.',
    )
    extract_model: str | None = Field(None, description="Model used for thread summarisation.")
    generate_memories: bool | None = Field(
        None,
        description='When `false`, newly created threads are stored with `memory_mode = "disabled"` in the state DB.',
    )
    max_raw_memories_for_consolidation: int | None = Field(
        None,
        description="Maximum number of recent raw memories retained for global consolidation.",
        ge=1,
        le=4096,
    )
    max_rollout_age_days: int | None = Field(
        None, description="Maximum age of the threads used for memories."
    )
    max_rollouts_per_startup: int | None = Field(
        None,
        description="Maximum number of rollout candidates processed per pass.",
        ge=1,
        le=128,
    )
    max_unused_days: int | None = Field(
        None,
        description="Maximum number of days since a memory was last used before it becomes ineligible for phase 2 selection.",
    )
    min_rate_limit_remaining_percent: int | None = Field(
        None,
        description="Minimum remaining percentage required in Codex rate-limit windows before memory startup runs.",
        ge=0,
        le=100,
    )
    min_rollout_idle_hours: int | None = Field(
        None,
        description="Minimum idle time between last thread activity and memory creation (hours). > 12h recommended.",
    )
    use_memories: bool | None = Field(
        None,
        description="When `false`, skip injecting memory usage instructions into developer prompts.",
    )


class ModelAvailabilityNuxConfig(RootModel[dict[str, int]]):
    root: dict[str, int] = Field(..., ge=0)


class ModelProviderAuthInfo(BaseModel):
    """
    Configuration for obtaining a provider bearer token from a command.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    args: list[str] | None = Field([], description="Command arguments.")
    command: str = Field(
        ...,
        description="Command to execute. Bare names are resolved via `PATH`; paths are resolved against `cwd`.",
    )
    cwd: AbsolutePathBuf | None = Field(
        None, description="Working directory used when running the token command."
    )
    refresh_interval_ms: int | None = Field(
        300000,
        description="Maximum age for the cached token before rerunning the command. Set to `0` to disable proactive refresh and only rerun after a 401 retry path.",
        ge=0,
    )
    timeout_ms: int | None = Field(
        5000,
        description="Maximum time to wait for the token command to exit successfully.",
        ge=1,
    )


class ModelProviderAwsAuthInfo(BaseModel):
    """
    AWS SigV4 auth configuration for a model provider.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    profile: str | None = Field(
        None,
        description="AWS profile name to use. When unset, the AWS SDK default chain decides.",
    )
    region: str | None = Field(
        None, description="AWS region to use for provider-specific endpoints."
    )


class MultiAgentV2ConfigToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = None
    hide_spawn_agent_metadata: bool | None = None
    max_concurrent_threads_per_session: int | None = Field(None, ge=1)
    min_wait_timeout_ms: int | None = Field(None, ge=1, le=3600000)
    root_agent_usage_hint_text: str | None = None
    subagent_usage_hint_text: str | None = None
    usage_hint_enabled: bool | None = None
    usage_hint_text: str | None = None


class NetworkDomainPermissionToml(StrEnum):
    allow = "allow"
    deny = "deny"


class NetworkDomainPermissionsToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class NetworkModeSchema(StrEnum):
    limited = "limited"
    full = "full"


class NetworkUnixSocketPermissionToml(StrEnum):
    allow = "allow"
    none = "none"


class NetworkUnixSocketPermissionsToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Notice(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    external_config_migration_prompts: ExternalConfigMigrationPrompts | None = Field(
        {
            "home": None,
            "home_last_prompted_at": None,
            "project_last_prompted_at": {},
            "projects": {},
        },
        description="Tracks scopes where external config migration prompts should be suppressed.",
        validate_default=True,
    )
    fast_default_opt_out: bool | None = Field(
        None,
        description="Tracks whether the user opted out of Codex-managed fast defaults.",
    )
    hide_full_access_warning: bool | None = Field(
        None,
        description="Tracks whether the user has acknowledged the full access warning prompt.",
    )
    hide_gpt_5_1_codex_max_migration_prompt: bool | None = Field(
        None,
        alias="hide_gpt-5.1-codex-max_migration_prompt",
        description="Tracks whether the user has seen the gpt-5.1-codex-max migration prompt",
    )
    hide_gpt5_1_migration_prompt: bool | None = Field(
        None, description="Tracks whether the user has seen the model migration prompt"
    )
    hide_rate_limit_model_nudge: bool | None = Field(
        None,
        description="Tracks whether the user opted out of the rate limit model switch reminder.",
    )
    hide_world_writable_warning: bool | None = Field(
        None,
        description="Tracks whether the user has acknowledged the Windows world-writable directories warning.",
    )
    model_migrations: dict[str, str] | None = Field(
        {},
        description="Tracks acknowledged model migrations as old->new model slug mappings.",
    )


class NotificationCondition1(StrEnum):
    """
    Emit TUI notifications only while the terminal is unfocused.
    """

    unfocused = "unfocused"


class NotificationCondition2(StrEnum):
    """
    Emit TUI notifications regardless of terminal focus.
    """

    always = "always"


class NotificationCondition(RootModel[NotificationCondition1 | NotificationCondition2]):
    root: NotificationCondition1 | NotificationCondition2


class NotificationMethod(StrEnum):
    auto = "auto"
    osc9 = "osc9"
    bel = "bel"


class Notifications(RootModel[bool | list[str]]):
    root: bool | list[str]


class OAuthCredentialsStoreMode1(StrEnum):
    """
    `Keyring` when available; otherwise, `File`. Credentials stored in the keyring will only be readable by Codex unless the user explicitly grants access via OS-level keyring access.
    """

    auto = "auto"


class OAuthCredentialsStoreMode2(StrEnum):
    """
    CODEX_HOME/.credentials.json This file will be readable to Codex and other applications running as the same user.
    """

    file = "file"


class OAuthCredentialsStoreMode3(StrEnum):
    """
    Keyring when available, otherwise fail.
    """

    keyring = "keyring"


class OAuthCredentialsStoreMode(
    RootModel[OAuthCredentialsStoreMode1 | OAuthCredentialsStoreMode2 | OAuthCredentialsStoreMode3]
):
    root: OAuthCredentialsStoreMode1 | OAuthCredentialsStoreMode2 | OAuthCredentialsStoreMode3 = (
        Field(..., description="Determine where Codex should store and read MCP credentials.")
    )


class OtelExporterKind1(StrEnum):
    """
    Which OTEL exporter to use.
    """

    none = "none"
    statsig = "statsig"


class OtelHttpProtocol1(StrEnum):
    """
    Binary payload
    """

    binary = "binary"


class OtelHttpProtocol2(StrEnum):
    """
    JSON payload
    """

    json = "json"


class OtelHttpProtocol(RootModel[OtelHttpProtocol1 | OtelHttpProtocol2]):
    root: OtelHttpProtocol1 | OtelHttpProtocol2


class OtelTlsConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ca_certificate: AbsolutePathBuf | None = Field(None, alias="ca-certificate")
    client_certificate: AbsolutePathBuf | None = Field(None, alias="client-certificate")
    client_private_key: AbsolutePathBuf | None = Field(None, alias="client-private-key")


class PermissionsToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )


class Personality(StrEnum):
    none = "none"
    friendly = "friendly"
    pragmatic = "pragmatic"


class PluginMcpServerConfig(BaseModel):
    """
    Policy settings for a plugin-provided MCP server.

    This intentionally excludes transport settings: plugin manifests own how the MCP server is launched, while user config owns enablement and tool policy.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    default_tools_approval_mode: AppToolApproval | None = Field(
        None,
        description="Approval mode for tools in this server unless a tool override exists.",
    )
    disabled_tools: list[str] | None = Field(
        None,
        description="Explicit deny-list of tools. These tools are removed after applying `enabled_tools`.",
    )
    enabled: bool | None = Field(
        True,
        description="When `false`, Codex skips initializing this plugin MCP server.",
    )
    enabled_tools: list[str] | None = Field(
        None, description="Explicit allow-list of tools exposed from this server."
    )
    tools: dict[str, McpServerToolConfig] | None = Field(
        None, description="Per-tool approval settings keyed by tool name."
    )


class RawMcpServerConfig(BaseModel):
    """
    Raw MCP config shape used for deserialization and supported-field JSON Schema generation.

    Fields that are accepted only to produce targeted validation errors should be skipped in the generated schema.

    Keep `TryFrom<RawMcpServerConfig> for McpServerConfig` exhaustively destructuring this struct so new TOML fields cannot be added here without updating the validation/mapping logic that produces [`McpServerConfig`].
    """

    model_config = ConfigDict(
        extra="allow",
    )
    args: list[str] | None = None
    bearer_token_env_var: str | None = None
    command: str | None = None
    cwd: str | None = None
    default_tools_approval_mode: AppToolApproval | None = None
    disabled_tools: list[str] | None = None
    enabled: bool | None = None
    enabled_tools: list[str] | None = None
    env: dict[str, Any] | None = None
    env_http_headers: dict[str, Any] | None = None
    env_vars: list[McpServerEnvVar] | None = None
    experimental_environment: str | None = None
    http_headers: dict[str, Any] | None = None
    name: str | None = Field(
        None,
        description="Legacy display-name field accepted for backward compatibility.",
    )
    oauth_resource: str | None = None
    required: bool | None = None
    scopes: list[str] | None = None
    startup_timeout_ms: int | None = Field(None, ge=0)
    startup_timeout_sec: float | None = None
    supports_parallel_tool_calls: bool | None = None
    tool_timeout_sec: float | None = None
    tools: dict[str, Any] | None = None
    url: str | None = None


class RealtimeAudioToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    microphone: str | None = None
    speaker: str | None = None


class RealtimeConversationVersion(StrEnum):
    v1 = "v1"
    v2 = "v2"


class RealtimeTransport(StrEnum):
    webrtc = "webrtc"
    websocket = "websocket"


class RealtimeVoice(StrEnum):
    alloy = "alloy"
    arbor = "arbor"
    ash = "ash"
    ballad = "ballad"
    breeze = "breeze"
    cedar = "cedar"
    coral = "coral"
    cove = "cove"
    echo = "echo"
    ember = "ember"
    juniper = "juniper"
    maple = "maple"
    marin = "marin"
    sage = "sage"
    shimmer = "shimmer"
    sol = "sol"
    spruce = "spruce"
    vale = "vale"
    verse = "verse"


class RealtimeWsMode(StrEnum):
    conversational = "conversational"
    transcription = "transcription"


class ReasoningEffort(StrEnum):
    """
    See https://platform.openai.com/docs/guides/reasoning?api-mode=responses#get-started-with-reasoning
    """

    none = "none"
    minimal = "minimal"
    low = "low"
    medium = "medium"
    high = "high"
    xhigh = "xhigh"


class ReasoningSummary1(StrEnum):
    """
    A summary of the reasoning performed by the model. This can be useful for debugging and understanding the model's reasoning process. See https://platform.openai.com/docs/guides/reasoning?api-mode=responses#reasoning-summaries
    """

    auto = "auto"
    concise = "concise"
    detailed = "detailed"


class ReasoningSummary2(StrEnum):
    """
    Option to disable reasoning summaries.
    """

    none = "none"


class ReasoningSummary(RootModel[ReasoningSummary1 | ReasoningSummary2]):
    root: ReasoningSummary1 | ReasoningSummary2 = Field(
        ...,
        description="A summary of the reasoning performed by the model. This can be useful for debugging and understanding the model's reasoning process. See https://platform.openai.com/docs/guides/reasoning?api-mode=responses#reasoning-summaries",
    )


class SandboxMode(StrEnum):
    read_only = "read-only"
    workspace_write = "workspace-write"
    danger_full_access = "danger-full-access"


class SandboxWorkspaceWrite(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    exclude_slash_tmp: bool | None = False
    exclude_tmpdir_env_var: bool | None = False
    network_access: bool | None = False
    writable_roots: list[AbsolutePathBuf] | None = Field([], validate_default=True)


class SessionPickerViewMode(StrEnum):
    """
    Preferred layout for the resume/fork session picker.
    """

    comfortable = "comfortable"
    dense = "dense"


class ShellEnvironmentPolicyInherit1(StrEnum):
    """
    "Core" environment variables for the platform. On UNIX, this would include HOME, LOGNAME, PATH, SHELL, and USER, among others.
    """

    core = "core"


class ShellEnvironmentPolicyInherit2(StrEnum):
    """
    Inherits the full environment from the parent process.
    """

    all = "all"


class ShellEnvironmentPolicyInherit3(StrEnum):
    """
    Do not inherit any environment variables from the parent process.
    """

    none = "none"


class ShellEnvironmentPolicyInherit(
    RootModel[
        ShellEnvironmentPolicyInherit1
        | ShellEnvironmentPolicyInherit2
        | ShellEnvironmentPolicyInherit3
    ]
):
    root: (
        ShellEnvironmentPolicyInherit1
        | ShellEnvironmentPolicyInherit2
        | ShellEnvironmentPolicyInherit3
    )


class ShellEnvironmentPolicyToml(BaseModel):
    """
    Policy for building the `env` when spawning a process via either the `shell` or `local_shell` tool.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    exclude: list[str] | None = Field(None, description="List of regular expressions.")
    experimental_use_profile: bool | None = None
    ignore_default_excludes: bool | None = None
    include_only: list[str] | None = Field(None, description="List of regular expressions.")
    inherit: ShellEnvironmentPolicyInherit | None = None
    set: dict[str, Any] | None = None


class SkillConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool
    name: str | None = Field(None, description="Name-based selector.")
    path: AbsolutePathBuf | None = Field(None, description="Path-based selector.")


class SkillsConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    bundled: BundledSkillsConfig | None = None
    config: list[SkillConfig] | None = None
    include_instructions: bool | None = Field(
        None,
        description="Whether turns receive the automatic skills instructions block.",
    )


class Type3(StrEnum):
    local = "local"


class ThreadStoreToml1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Type3


class ThreadStoreToml(RootModel[ThreadStoreToml1]):
    root: ThreadStoreToml1


class ToolSuggestDiscoverableType(StrEnum):
    connector = "connector"
    plugin = "plugin"


class TrustLevel(StrEnum):
    """
    Represents the trust level for a project directory. This determines the approval policy and sandbox mode applied.
    """

    trusted = "trusted"
    untrusted = "untrusted"


class TuiApprovalKeymap(BaseModel):
    """
    Approval overlay keybindings.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    approve: KeybindingsSpec | None = Field(None, description="Approve the primary option.")
    approve_for_prefix: KeybindingsSpec | None = Field(
        None, description="Approve with exec-policy prefix when that option exists."
    )
    approve_for_session: KeybindingsSpec | None = Field(
        None, description="Approve for session when that option exists."
    )
    cancel: KeybindingsSpec | None = Field(None, description="Cancel an elicitation request.")
    decline: KeybindingsSpec | None = Field(
        None, description="Decline and provide corrective guidance."
    )
    deny: KeybindingsSpec | None = Field(
        None, description="Deny without providing follow-up guidance."
    )
    open_fullscreen: KeybindingsSpec | None = Field(
        None, description="Open the full-screen approval details view."
    )
    open_thread: KeybindingsSpec | None = Field(
        None,
        description="Open the thread that requested approval when shown from another thread.",
    )


class TuiChatKeymap(BaseModel):
    """
    Chat context keybindings.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    decrease_reasoning_effort: KeybindingsSpec | None = Field(
        None, description="Decrease the active reasoning effort."
    )
    edit_queued_message: KeybindingsSpec | None = Field(
        None, description="Edit the most recently queued message."
    )
    increase_reasoning_effort: KeybindingsSpec | None = Field(
        None, description="Increase the active reasoning effort."
    )


class TuiComposerKeymap(BaseModel):
    """
    Composer context keybindings. These override corresponding `global` actions.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    history_search_next: KeybindingsSpec | None = Field(
        None, description="Move to the next match in reverse history search."
    )
    history_search_previous: KeybindingsSpec | None = Field(
        None, description="Open reverse history search or move to the previous match."
    )
    queue: KeybindingsSpec | None = Field(
        None, description="Queue the current composer draft while a task is running."
    )
    submit: KeybindingsSpec | None = Field(None, description="Submit the current composer draft.")
    toggle_shortcuts: KeybindingsSpec | None = Field(
        None, description="Toggle the composer shortcut overlay."
    )


class TuiEditorKeymap(BaseModel):
    """
    Editor context keybindings for text editing inside text areas.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    delete_backward: KeybindingsSpec | None = Field(
        None, description="Delete one grapheme to the left."
    )
    delete_backward_word: KeybindingsSpec | None = Field(
        None, description="Delete the previous word."
    )
    delete_forward: KeybindingsSpec | None = Field(
        None, description="Delete one grapheme to the right."
    )
    delete_forward_word: KeybindingsSpec | None = Field(None, description="Delete the next word.")
    insert_newline: KeybindingsSpec | None = Field(
        None, description="Insert a newline in the editor."
    )
    kill_line_end: KeybindingsSpec | None = Field(
        None, description="Kill text from cursor to line end."
    )
    kill_line_start: KeybindingsSpec | None = Field(
        None, description="Kill text from cursor to line start."
    )
    kill_whole_line: KeybindingsSpec | None = Field(None, description="Kill the current line.")
    move_down: KeybindingsSpec | None = Field(None, description="Move cursor down one visual line.")
    move_left: KeybindingsSpec | None = Field(None, description="Move cursor left by one grapheme.")
    move_line_end: KeybindingsSpec | None = Field(None, description="Move cursor to end of line.")
    move_line_start: KeybindingsSpec | None = Field(
        None, description="Move cursor to beginning of line."
    )
    move_right: KeybindingsSpec | None = Field(
        None, description="Move cursor right by one grapheme."
    )
    move_up: KeybindingsSpec | None = Field(None, description="Move cursor up one visual line.")
    move_word_left: KeybindingsSpec | None = Field(
        None, description="Move cursor to beginning of previous word."
    )
    move_word_right: KeybindingsSpec | None = Field(
        None, description="Move cursor to end of next word."
    )
    yank: KeybindingsSpec | None = Field(None, description="Yank the kill buffer.")


class TuiGlobalKeymap(BaseModel):
    """
    Global keybindings. These are used when a context does not define an override.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    clear_terminal: KeybindingsSpec | None = Field(None, description="Clear the terminal UI.")
    copy_: KeybindingsSpec | None = Field(
        None, alias="copy", description="Copy the last agent response to the clipboard."
    )
    open_external_editor: KeybindingsSpec | None = Field(
        None, description="Open the external editor for the current draft."
    )
    open_transcript: KeybindingsSpec | None = Field(
        None, description="Open the transcript overlay."
    )
    queue: KeybindingsSpec | None = Field(
        None, description="Queue the current composer draft while a task is running."
    )
    submit: KeybindingsSpec | None = Field(None, description="Submit the current composer draft.")
    toggle_fast_mode: KeybindingsSpec | None = Field(None, description="Toggle Fast mode.")
    toggle_raw_output: KeybindingsSpec | None = Field(
        None,
        description="Toggle raw scrollback mode for copy-friendly transcript selection.",
    )
    toggle_shortcuts: KeybindingsSpec | None = Field(
        None, description="Toggle the composer shortcut overlay."
    )
    toggle_vim_mode: KeybindingsSpec | None = Field(
        None, description="Toggle Vim mode for the composer input."
    )


class TuiListKeymap(BaseModel):
    """
    List selection context keybindings for popup-style selectable lists.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    accept: KeybindingsSpec | None = Field(None, description="Accept current selection.")
    cancel: KeybindingsSpec | None = Field(None, description="Cancel and close selection view.")
    move_down: KeybindingsSpec | None = Field(None, description="Move list selection down.")
    move_up: KeybindingsSpec | None = Field(None, description="Move list selection up.")


class TuiPagerKeymap(BaseModel):
    """
    Pager context keybindings for transcript and static overlays.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    close: KeybindingsSpec | None = Field(None, description="Close the pager overlay.")
    close_transcript: KeybindingsSpec | None = Field(
        None, description="Close the transcript overlay via its dedicated toggle key."
    )
    half_page_down: KeybindingsSpec | None = Field(None, description="Scroll down by half a page.")
    half_page_up: KeybindingsSpec | None = Field(None, description="Scroll up by half a page.")
    jump_bottom: KeybindingsSpec | None = Field(None, description="Jump to the end.")
    jump_top: KeybindingsSpec | None = Field(None, description="Jump to the beginning.")
    page_down: KeybindingsSpec | None = Field(None, description="Scroll down by one page.")
    page_up: KeybindingsSpec | None = Field(None, description="Scroll up by one page.")
    scroll_down: KeybindingsSpec | None = Field(None, description="Scroll down by one row.")
    scroll_up: KeybindingsSpec | None = Field(None, description="Scroll up by one row.")


class TuiVimNormalKeymap(BaseModel):
    """
    Vim normal-mode keybindings for modal editing inside text areas.

    Actions that use uppercase letters (like `A` for append-line-end) should be specified as `shift-a` in config; the runtime matcher handles cross-terminal shift-reporting differences automatically.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    append_after_cursor: KeybindingsSpec | None = Field(
        None, description="Enter insert mode after cursor (`a`)."
    )
    append_line_end: KeybindingsSpec | None = Field(
        None, description="Enter insert mode at end of line (`A`)."
    )
    cancel_operator: KeybindingsSpec | None = Field(
        None, description="Cancel a pending operator and return to normal mode."
    )
    delete_char: KeybindingsSpec | None = Field(
        None, description="Delete character under cursor (`x`)."
    )
    delete_to_line_end: KeybindingsSpec | None = Field(
        None, description="Delete from cursor to end of line (`D`)."
    )
    enter_insert: KeybindingsSpec | None = Field(
        None, description="Enter insert mode at cursor (`i`)."
    )
    insert_line_start: KeybindingsSpec | None = Field(
        None, description="Enter insert mode at first non-blank of line (`I`)."
    )
    move_down: KeybindingsSpec | None = Field(
        None,
        description="Move cursor down (`j`), or recall newer composer history at history boundaries.",
    )
    move_left: KeybindingsSpec | None = Field(None, description="Move cursor left (`h`).")
    move_line_end: KeybindingsSpec | None = Field(
        None, description="Move cursor to end of line (`$`)."
    )
    move_line_start: KeybindingsSpec | None = Field(
        None, description="Move cursor to start of line (`0`)."
    )
    move_right: KeybindingsSpec | None = Field(None, description="Move cursor right (`l`).")
    move_up: KeybindingsSpec | None = Field(
        None,
        description="Move cursor up (`k`), or recall older composer history at history boundaries.",
    )
    move_word_backward: KeybindingsSpec | None = Field(
        None, description="Move cursor to start of previous word (`b`)."
    )
    move_word_end: KeybindingsSpec | None = Field(
        None, description="Move cursor to end of current/next word (`e`)."
    )
    move_word_forward: KeybindingsSpec | None = Field(
        None, description="Move cursor to start of next word (`w`)."
    )
    open_line_above: KeybindingsSpec | None = Field(
        None, description="Open a new line above and enter insert mode (`O`)."
    )
    open_line_below: KeybindingsSpec | None = Field(
        None, description="Open a new line below and enter insert mode (`o`)."
    )
    paste_after: KeybindingsSpec | None = Field(None, description="Paste after cursor (`p`).")
    start_delete_operator: KeybindingsSpec | None = Field(
        None, description="Begin delete operator; next key selects motion (`d`)."
    )
    start_yank_operator: KeybindingsSpec | None = Field(
        None, description="Begin yank operator; next key selects motion (`y`)."
    )
    yank_line: KeybindingsSpec | None = Field(None, description="Yank the entire line (`Y`).")


class TuiVimOperatorKeymap(BaseModel):
    """
    Vim operator-pending keybindings for modal editing inside text areas.

    This context is active only while waiting for a motion after `d` or `y`. Repeating the operator key (`dd`, `yy`) targets the entire line. Pressing `Esc` cancels the pending operator and returns to normal mode without modifying text.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    cancel: KeybindingsSpec | None = Field(
        None, description="Cancel the pending operator and return to normal mode."
    )
    delete_line: KeybindingsSpec | None = Field(
        None, description="Repeat delete operator to delete the whole line (`dd`)."
    )
    motion_down: KeybindingsSpec | None = Field(None, description="Motion: down one line (`j`).")
    motion_left: KeybindingsSpec | None = Field(None, description="Motion: left (`h`).")
    motion_line_end: KeybindingsSpec | None = Field(
        None, description="Motion: to end of line (`$`)."
    )
    motion_line_start: KeybindingsSpec | None = Field(
        None, description="Motion: to start of line (`0`)."
    )
    motion_right: KeybindingsSpec | None = Field(None, description="Motion: right (`l`).")
    motion_up: KeybindingsSpec | None = Field(None, description="Motion: up one line (`k`).")
    motion_word_backward: KeybindingsSpec | None = Field(
        None, description="Motion: to start of previous word (`b`)."
    )
    motion_word_end: KeybindingsSpec | None = Field(
        None, description="Motion: to end of current/next word (`e`)."
    )
    motion_word_forward: KeybindingsSpec | None = Field(
        None, description="Motion: to start of next word (`w`)."
    )
    yank_line: KeybindingsSpec | None = Field(
        None, description="Repeat yank operator to yank the whole line (`yy`)."
    )


class UriBasedFileOpener1(StrEnum):
    vscode = "vscode"
    vscode_insiders = "vscode-insiders"
    windsurf = "windsurf"
    cursor = "cursor"


class UriBasedFileOpener2(StrEnum):
    """
    Option to disable the URI-based file opener.
    """

    none = "none"


class UriBasedFileOpener(RootModel[UriBasedFileOpener1 | UriBasedFileOpener2]):
    root: UriBasedFileOpener1 | UriBasedFileOpener2


class Verbosity(StrEnum):
    """
    Controls output length/detail on GPT-5 models via the Responses API. Serialized with lowercase values to match the OpenAI API.
    """

    low = "low"
    medium = "medium"
    high = "high"


class WebSearchContextSize(StrEnum):
    low = "low"
    medium = "medium"
    high = "high"


class WebSearchLocation(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    city: str | None = None
    country: str | None = None
    region: str | None = None
    timezone: str | None = None


class WebSearchMode(StrEnum):
    disabled = "disabled"
    cached = "cached"
    live = "live"


class WebSearchToolConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    allowed_domains: list[str] | None = None
    context_size: WebSearchContextSize | None = None
    location: WebSearchLocation | None = None


class WindowsSandboxModeToml(StrEnum):
    elevated = "elevated"
    unelevated = "unelevated"


class WindowsToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    sandbox: WindowsSandboxModeToml | None = None
    sandbox_private_desktop: bool | None = Field(
        None,
        description="Defaults to `true`. Set to `false` to launch the final sandboxed child process on `Winsta0\\\\Default` instead of a private desktop.",
    )


class WireApi1(StrEnum):
    """
    The Responses API exposed by OpenAI at `/v1/responses`.
    """

    responses = "responses"


class WireApi(RootModel[WireApi1]):
    root: WireApi1 = Field(..., description="Wire protocol that the provider speaks.")


class AppConfig(BaseModel):
    """
    Config values for a single app/connector.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    default_tools_approval_mode: AppToolApproval | None = Field(
        None,
        description="Approval mode for tools in this app unless a tool override exists.",
    )
    default_tools_enabled: bool | None = Field(
        None, description="Whether tools are enabled by default for this app."
    )
    destructive_enabled: bool | None = Field(
        None,
        description="Whether tools with `destructive_hint = true` are allowed for this app.",
    )
    enabled: bool | None = Field(True, description="When `false`, Codex does not surface this app.")
    open_world_enabled: bool | None = Field(
        None,
        description="Whether tools with `open_world_hint = true` are allowed for this app.",
    )
    tools: AppToolsConfig | None = Field(None, description="Per-tool settings for this app.")


class AppsConfigToml(BaseModel):
    """
    App/connector settings loaded from `config.toml`.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    field_default: AppsDefaultConfig | None = Field(
        None, alias="_default", description="Default settings for all apps."
    )


class AskForApproval4(BaseModel):
    """
    Fine-grained controls for individual approval flows.

    When a field is `true`, commands in that category are allowed. When it is `false`, those requests are automatically rejected instead of shown to the user.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    granular: GranularApprovalConfig


class AskForApproval(
    RootModel[
        AskForApproval1 | AskForApproval2 | AskForApproval3 | AskForApproval4 | AskForApproval5
    ]
):
    root: (
        AskForApproval1 | AskForApproval2 | AskForApproval3 | AskForApproval4 | AskForApproval5
    ) = Field(
        ...,
        description="Determines the conditions under which the user is consulted to approve running the command proposed by Codex.",
    )


class FeatureTomlForMultiAgentV2ConfigToml(RootModel[bool | MultiAgentV2ConfigToml]):
    root: bool | MultiAgentV2ConfigToml


class History(BaseModel):
    """
    Settings that govern if and what will be written to `~/.codex/history.jsonl`.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    max_bytes: int | None = Field(
        None,
        description="If set, the maximum size of the history file in bytes. The oldest entries are dropped once the file exceeds this limit.",
        ge=0,
    )
    persistence: HistoryPersistence | None = Field(
        "save-all",
        description="If true, history entries will not be written to disk.",
        validate_default=True,
    )


class HooksToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    permission_request: list[MatcherGroup] | None = Field(
        [], alias="PermissionRequest", validate_default=True
    )
    post_compact: list[MatcherGroup] | None = Field([], alias="PostCompact", validate_default=True)
    post_tool_use: list[MatcherGroup] | None = Field([], alias="PostToolUse", validate_default=True)
    pre_compact: list[MatcherGroup] | None = Field([], alias="PreCompact", validate_default=True)
    pre_tool_use: list[MatcherGroup] | None = Field([], alias="PreToolUse", validate_default=True)
    session_start: list[MatcherGroup] | None = Field(
        [], alias="SessionStart", validate_default=True
    )
    stop: list[MatcherGroup] | None = Field([], alias="Stop", validate_default=True)
    user_prompt_submit: list[MatcherGroup] | None = Field(
        [], alias="UserPromptSubmit", validate_default=True
    )
    state: dict[str, HookStateToml] | None = None


class MarketplaceConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    last_revision: str | None = Field(
        None,
        description="Git revision Codex last successfully activated for this marketplace.",
    )
    last_updated: str | None = Field(
        None,
        description="Last time Codex successfully added or refreshed this marketplace.",
    )
    ref: str | None = Field(None, description="Git ref to check out when `source_type` is `git`.")
    source: str | None = Field(
        None, description="Source location used when the marketplace was added."
    )
    source_type: MarketplaceSourceType | None = Field(
        None, description="Source kind used to install this marketplace."
    )
    sparse_paths: list[str] | None = Field(
        None, description="Sparse checkout paths used when `source_type` is `git`."
    )


class ModelProviderInfo(BaseModel):
    """
    Serializable representation of a provider definition.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    auth: ModelProviderAuthInfo | None = Field(
        None, description="Command-backed bearer-token configuration for this provider."
    )
    aws: ModelProviderAwsAuthInfo | None = Field(
        None, description="AWS SigV4 auth configuration for this provider."
    )
    base_url: str | None = Field(
        None, description="Base URL for the provider's OpenAI-compatible API."
    )
    env_http_headers: dict[str, Any] | None = Field(
        None,
        description="Optional HTTP headers to include in requests to this provider where the (key, value) pairs are the header name and _environment variable_ whose value should be used. If the environment variable is not set, or the value is empty, the header will not be included in the request.",
    )
    env_key: str | None = Field(
        None,
        description="Environment variable that stores the user's API key for this provider.",
    )
    env_key_instructions: str | None = Field(
        None,
        description="Optional instructions to help the user get a valid value for the variable and set it.",
    )
    experimental_bearer_token: str | None = Field(
        None,
        description="Value to use with `Authorization: Bearer <token>` header. Use of this config is discouraged in favor of `env_key` for security reasons, but this may be necessary when using this programmatically.",
    )
    http_headers: dict[str, Any] | None = Field(
        None,
        description="Additional HTTP headers to include in requests to this provider where the (key, value) pairs are the header name and value.",
    )
    name: str | None = Field("", description="Friendly display name.")
    query_params: dict[str, Any] | None = Field(
        None, description="Optional query parameters to append to the base URL."
    )
    request_max_retries: int | None = Field(
        None,
        description="Maximum number of times to retry a failed HTTP request to this provider.",
        ge=0,
    )
    requires_openai_auth: bool | None = Field(
        False,
        description='Does this provider require an OpenAI API Key or ChatGPT login token? If true, user is presented with login screen on first run, and login preference and token/key are stored in auth.json. If false (which is the default), login screen is skipped, and API key (if needed) comes from the "env_key" environment variable.',
    )
    stream_idle_timeout_ms: int | None = Field(
        None,
        description="Idle timeout (in milliseconds) to wait for activity on a streaming response before treating the connection as lost.",
        ge=0,
    )
    stream_max_retries: int | None = Field(
        None,
        description="Number of times to retry reconnecting a dropped streaming response before failing.",
        ge=0,
    )
    supports_websockets: bool | None = Field(
        False,
        description="Whether this provider supports the Responses API WebSocket transport.",
    )
    websocket_connect_timeout_ms: int | None = Field(
        None,
        description="Maximum time (in milliseconds) to wait for a websocket connection attempt before treating it as failed.",
        ge=0,
    )
    wire_api: WireApi | None = Field(
        "responses",
        description="Which wire protocol this provider expects.",
        validate_default=True,
    )


class NetworkToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    allow_local_binding: bool | None = None
    allow_upstream_proxy: bool | None = None
    dangerously_allow_all_unix_sockets: bool | None = None
    dangerously_allow_non_loopback_proxy: bool | None = None
    domains: NetworkDomainPermissionsToml | None = None
    enable_socks5: bool | None = None
    enable_socks5_udp: bool | None = None
    enabled: bool | None = None
    mode: NetworkModeSchema | None = None
    proxy_url: str | None = None
    socks_url: str | None = None
    unix_sockets: NetworkUnixSocketPermissionsToml | None = None


class OtlpHttp(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    endpoint: str
    headers: dict[str, str] | None = {}
    protocol: OtelHttpProtocol
    tls: OtelTlsConfig | None = None


class OtelExporterKind2(BaseModel):
    """
    Which OTEL exporter to use.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    otlp_http: OtlpHttp = Field(..., alias="otlp-http")


class OtlpGrpc(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    endpoint: str
    headers: dict[str, str] | None = {}
    tls: OtelTlsConfig | None = None


class OtelExporterKind3(BaseModel):
    """
    Which OTEL exporter to use.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    otlp_grpc: OtlpGrpc = Field(..., alias="otlp-grpc")


class OtelExporterKind(RootModel[OtelExporterKind1 | OtelExporterKind2 | OtelExporterKind3]):
    root: OtelExporterKind1 | OtelExporterKind2 | OtelExporterKind3 = Field(
        ..., description="Which OTEL exporter to use."
    )


class PermissionProfileToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    filesystem: FilesystemPermissionsToml | None = None
    network: NetworkToml | None = None


class PluginConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    enabled: bool | None = True
    mcp_servers: dict[str, PluginMcpServerConfig] | None = Field(
        None,
        description="Per-MCP-server policy overlays for MCP servers contributed by this plugin.",
    )


class ProfileTui(BaseModel):
    """
    TUI settings supported inside a named profile.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    session_picker_view: SessionPickerViewMode | None = Field(
        None, description="Preferred layout for resume/fork session picker results."
    )


class ProjectConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    trust_level: TrustLevel | None = None


class RealtimeToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    transport: RealtimeTransport | None = None
    type: RealtimeWsMode | None = None
    version: RealtimeConversationVersion | None = None
    voice: RealtimeVoice | None = None


class ToolSuggestDisabledTool(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    type: ToolSuggestDiscoverableType


class ToolSuggestDiscoverable(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    type: ToolSuggestDiscoverableType


class ToolsToml(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    view_image: bool | None = Field(
        None,
        description="Enable the `view_image` tool that lets the agent attach local images.",
    )
    web_search: WebSearchToolConfig | None = None


class TuiKeymap(BaseModel):
    """
    Raw keymap configuration from `[tui.keymap]`.

    Each context contains action-level overrides. Missing actions inherit from built-in defaults, and selected chat/composer actions can fall back through `global` during runtime resolution.

    This type is intentionally a persistence shape, not the structure used by input handlers. Runtime consumers should resolve it into `RuntimeKeymap` first so precedence, empty-list unbinding, and duplicate-key validation are applied consistently.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    approval: TuiApprovalKeymap | None = Field(
        {
            "approve": None,
            "approve_for_prefix": None,
            "approve_for_session": None,
            "cancel": None,
            "decline": None,
            "deny": None,
            "open_fullscreen": None,
            "open_thread": None,
        },
        validate_default=True,
    )
    chat: TuiChatKeymap | None = Field(
        {
            "decrease_reasoning_effort": None,
            "edit_queued_message": None,
            "increase_reasoning_effort": None,
        },
        validate_default=True,
    )
    composer: TuiComposerKeymap | None = Field(
        {
            "history_search_next": None,
            "history_search_previous": None,
            "queue": None,
            "submit": None,
            "toggle_shortcuts": None,
        },
        validate_default=True,
    )
    editor: TuiEditorKeymap | None = Field(
        {
            "delete_backward": None,
            "delete_backward_word": None,
            "delete_forward": None,
            "delete_forward_word": None,
            "insert_newline": None,
            "kill_line_end": None,
            "kill_line_start": None,
            "kill_whole_line": None,
            "move_down": None,
            "move_left": None,
            "move_line_end": None,
            "move_line_start": None,
            "move_right": None,
            "move_up": None,
            "move_word_left": None,
            "move_word_right": None,
            "yank": None,
        },
        validate_default=True,
    )
    global_: TuiGlobalKeymap | None = Field(
        {
            "clear_terminal": None,
            "copy": None,
            "open_external_editor": None,
            "open_transcript": None,
            "queue": None,
            "submit": None,
            "toggle_fast_mode": None,
            "toggle_raw_output": None,
            "toggle_shortcuts": None,
            "toggle_vim_mode": None,
        },
        alias="global",
        validate_default=True,
    )
    list: TuiListKeymap | None = Field(
        {"accept": None, "cancel": None, "move_down": None, "move_up": None},
        validate_default=True,
    )
    pager: TuiPagerKeymap | None = Field(
        {
            "close": None,
            "close_transcript": None,
            "half_page_down": None,
            "half_page_up": None,
            "jump_bottom": None,
            "jump_top": None,
            "page_down": None,
            "page_up": None,
            "scroll_down": None,
            "scroll_up": None,
        },
        validate_default=True,
    )
    vim_normal: TuiVimNormalKeymap | None = Field(
        {
            "append_after_cursor": None,
            "append_line_end": None,
            "cancel_operator": None,
            "delete_char": None,
            "delete_to_line_end": None,
            "enter_insert": None,
            "insert_line_start": None,
            "move_down": None,
            "move_left": None,
            "move_line_end": None,
            "move_line_start": None,
            "move_right": None,
            "move_up": None,
            "move_word_backward": None,
            "move_word_end": None,
            "move_word_forward": None,
            "open_line_above": None,
            "open_line_below": None,
            "paste_after": None,
            "start_delete_operator": None,
            "start_yank_operator": None,
            "yank_line": None,
        },
        validate_default=True,
    )
    vim_operator: TuiVimOperatorKeymap | None = Field(
        {
            "cancel": None,
            "delete_line": None,
            "motion_down": None,
            "motion_left": None,
            "motion_line_end": None,
            "motion_line_start": None,
            "motion_right": None,
            "motion_up": None,
            "motion_word_backward": None,
            "motion_word_end": None,
            "motion_word_forward": None,
            "yank_line": None,
        },
        validate_default=True,
    )


class Features(BaseModel):
    """
    Centralized feature flags (new). Prefer this over individual toggles.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    apply_patch_freeform: bool | None = None
    apply_patch_streaming_events: bool | None = None
    apps: bool | None = None
    apps_mcp_path_override: FeatureTomlForAppsMcpPathOverrideConfigToml | None = None
    auth_elicitation: bool | None = None
    browser_use: bool | None = None
    browser_use_external: bool | None = None
    builtin_mcp: bool | None = None
    child_agents_md: bool | None = None
    chronicle: bool | None = None
    code_mode: bool | None = None
    code_mode_only: bool | None = None
    codex_git_commit: bool | None = None
    codex_hooks: bool | None = None
    collab: bool | None = None
    collaboration_modes: bool | None = None
    computer_use: bool | None = None
    connectors: bool | None = None
    default_mode_request_user_input: bool | None = None
    elevated_windows_sandbox: bool | None = None
    enable_experimental_windows_sandbox: bool | None = None
    enable_fanout: bool | None = None
    enable_mcp_apps: bool | None = None
    enable_request_compression: bool | None = None
    exec_permission_approvals: bool | None = None
    experimental_use_freeform_apply_patch: bool | None = None
    experimental_use_unified_exec_tool: bool | None = None
    experimental_windows_sandbox: bool | None = None
    external_migration: bool | None = None
    fast_mode: bool | None = None
    goals: bool | None = None
    guardian_approval: bool | None = None
    hooks: bool | None = None
    image_detail_original: bool | None = None
    image_generation: bool | None = None
    in_app_browser: bool | None = None
    include_apply_patch_tool: bool | None = None
    js_repl: bool | None = None
    js_repl_tools_only: bool | None = None
    memories: bool | None = None
    memory_tool: bool | None = None
    multi_agent: bool | None = None
    multi_agent_v2: FeatureTomlForMultiAgentV2ConfigToml | None = None
    personality: bool | None = None
    plugin_hooks: bool | None = None
    plugins: bool | None = None
    prevent_idle_sleep: bool | None = None
    realtime_conversation: bool | None = None
    remote_compaction_v2: bool | None = None
    remote_control: bool | None = None
    remote_models: bool | None = None
    remote_plugin: bool | None = None
    request_permissions: bool | None = None
    request_permissions_tool: bool | None = None
    request_rule: bool | None = None
    responses_websocket_response_processed: bool | None = None
    responses_websockets: bool | None = None
    responses_websockets_v2: bool | None = None
    runtime_metrics: bool | None = None
    search_tool: bool | None = None
    shell_snapshot: bool | None = None
    shell_tool: bool | None = None
    shell_zsh_fork: bool | None = None
    skill_env_var_dependency_prompt: bool | None = None
    skill_mcp_dependency_install: bool | None = None
    sqlite: bool | None = None
    steer: bool | None = None
    telepathy: bool | None = None
    terminal_resize_reflow: bool | None = None
    tool_call_mcp_elicitation: bool | None = None
    tool_search: bool | None = None
    tool_search_always_defer_mcp_tools: bool | None = None
    tool_suggest: bool | None = None
    tui_app_server: bool | None = None
    unavailable_dummy_tools: bool | None = None
    undo: bool | None = None
    unified_exec: bool | None = None
    use_legacy_landlock: bool | None = None
    use_linux_sandbox_bwrap: bool | None = None
    web_search: bool | None = None
    web_search_cached: bool | None = None
    web_search_request: bool | None = None
    workspace_dependencies: bool | None = None
    workspace_owner_usage_nudge: bool | None = None


class Features1(BaseModel):
    """
    Optional feature toggles scoped to this profile.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    apply_patch_freeform: bool | None = None
    apply_patch_streaming_events: bool | None = None
    apps: bool | None = None
    apps_mcp_path_override: FeatureTomlForAppsMcpPathOverrideConfigToml | None = None
    auth_elicitation: bool | None = None
    browser_use: bool | None = None
    browser_use_external: bool | None = None
    builtin_mcp: bool | None = None
    child_agents_md: bool | None = None
    chronicle: bool | None = None
    code_mode: bool | None = None
    code_mode_only: bool | None = None
    codex_git_commit: bool | None = None
    codex_hooks: bool | None = None
    collab: bool | None = None
    collaboration_modes: bool | None = None
    computer_use: bool | None = None
    connectors: bool | None = None
    default_mode_request_user_input: bool | None = None
    elevated_windows_sandbox: bool | None = None
    enable_experimental_windows_sandbox: bool | None = None
    enable_fanout: bool | None = None
    enable_mcp_apps: bool | None = None
    enable_request_compression: bool | None = None
    exec_permission_approvals: bool | None = None
    experimental_use_freeform_apply_patch: bool | None = None
    experimental_use_unified_exec_tool: bool | None = None
    experimental_windows_sandbox: bool | None = None
    external_migration: bool | None = None
    fast_mode: bool | None = None
    goals: bool | None = None
    guardian_approval: bool | None = None
    hooks: bool | None = None
    image_detail_original: bool | None = None
    image_generation: bool | None = None
    in_app_browser: bool | None = None
    include_apply_patch_tool: bool | None = None
    js_repl: bool | None = None
    js_repl_tools_only: bool | None = None
    memories: bool | None = None
    memory_tool: bool | None = None
    multi_agent: bool | None = None
    multi_agent_v2: FeatureTomlForMultiAgentV2ConfigToml | None = None
    personality: bool | None = None
    plugin_hooks: bool | None = None
    plugins: bool | None = None
    prevent_idle_sleep: bool | None = None
    realtime_conversation: bool | None = None
    remote_compaction_v2: bool | None = None
    remote_control: bool | None = None
    remote_models: bool | None = None
    remote_plugin: bool | None = None
    request_permissions: bool | None = None
    request_permissions_tool: bool | None = None
    request_rule: bool | None = None
    responses_websocket_response_processed: bool | None = None
    responses_websockets: bool | None = None
    responses_websockets_v2: bool | None = None
    runtime_metrics: bool | None = None
    search_tool: bool | None = None
    shell_snapshot: bool | None = None
    shell_tool: bool | None = None
    shell_zsh_fork: bool | None = None
    skill_env_var_dependency_prompt: bool | None = None
    skill_mcp_dependency_install: bool | None = None
    sqlite: bool | None = None
    steer: bool | None = None
    telepathy: bool | None = None
    terminal_resize_reflow: bool | None = None
    tool_call_mcp_elicitation: bool | None = None
    tool_search: bool | None = None
    tool_search_always_defer_mcp_tools: bool | None = None
    tool_suggest: bool | None = None
    tui_app_server: bool | None = None
    unavailable_dummy_tools: bool | None = None
    undo: bool | None = None
    unified_exec: bool | None = None
    use_legacy_landlock: bool | None = None
    use_linux_sandbox_bwrap: bool | None = None
    web_search: bool | None = None
    web_search_cached: bool | None = None
    web_search_request: bool | None = None
    workspace_dependencies: bool | None = None
    workspace_owner_usage_nudge: bool | None = None


class ConfigProfile(BaseModel):
    """
    Collection of common configuration options that a user can define as a unit in `config.toml`.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    analytics: AnalyticsConfigToml | None = None
    approval_policy: AskForApproval | None = None
    approvals_reviewer: ApprovalsReviewer | None = None
    chatgpt_base_url: str | None = None
    experimental_compact_prompt_file: AbsolutePathBuf | None = None
    experimental_use_freeform_apply_patch: bool | None = None
    experimental_use_unified_exec_tool: bool | None = None
    features: Features1 | None = Field(
        None, description="Optional feature toggles scoped to this profile."
    )
    include_apply_patch_tool: bool | None = None
    include_apps_instructions: bool | None = None
    include_environment_context: bool | None = None
    include_permissions_instructions: bool | None = None
    model: str | None = None
    model_catalog_json: AbsolutePathBuf | None = Field(
        None,
        description="Optional path to a JSON model catalog (applied on startup only).",
    )
    model_instructions_file: AbsolutePathBuf | None = Field(
        None, description="Optional path to a file containing model instructions."
    )
    model_provider: str | None = Field(
        None,
        description="The key in the `model_providers` map identifying the [`ModelProviderInfo`] to use.",
    )
    model_reasoning_effort: ReasoningEffort | None = None
    model_reasoning_summary: ReasoningSummary | None = None
    model_verbosity: Verbosity | None = None
    oss_provider: str | None = None
    personality: Personality | None = None
    plan_mode_reasoning_effort: ReasoningEffort | None = None
    sandbox_mode: SandboxMode | None = None
    service_tier: str | None = Field(
        None,
        description="Optional explicit service tier request id for new turns (for example `priority` or `flex`; legacy `fast` also works).",
    )
    tools: ToolsToml | None = None
    tools_view_image: bool | None = None
    tui: ProfileTui | None = Field(None, description="TUI settings scoped to this profile.")
    web_search: WebSearchMode | None = None
    windows: WindowsToml | None = None
    zsh_path: AbsolutePathBuf | None = Field(
        None,
        description="Optional absolute path to patched zsh used by zsh-exec-bridge-backed shell execution.",
    )


class OtelConfigToml(BaseModel):
    """
    OTEL settings loaded from config.toml. Fields are optional so we can apply defaults.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    environment: str | None = Field(
        None,
        description="Mark traces with environment (dev, staging, prod, test). Defaults to dev.",
    )
    exporter: OtelExporterKind | None = Field(None, description="Optional log exporter")
    log_user_prompt: bool | None = Field(None, description="Log user prompt in traces")
    metrics_exporter: OtelExporterKind | None = Field(None, description="Optional metrics exporter")
    span_attributes: dict[str, Any] | None = Field(
        None, description="Attributes to add to every exported trace span."
    )
    trace_exporter: OtelExporterKind | None = Field(None, description="Optional trace exporter")
    tracestate: dict[str, Any] | None = Field(
        None,
        description="Semicolon-separated `key:value` fields to upsert into W3C tracestate members.",
    )


class ToolSuggestConfig(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    disabled_tools: list[ToolSuggestDisabledTool] | None = Field([], validate_default=True)
    discoverables: list[ToolSuggestDiscoverable] | None = Field([], validate_default=True)


class Tui(BaseModel):
    """
    Collection of settings that are specific to the TUI.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    alternate_screen: AltScreenMode | None = Field(
        "auto",
        description="Controls whether the TUI uses the terminal's alternate screen buffer.\n\n- `auto` (default): Disable alternate screen in Zellij, enable elsewhere. - `always`: Always use alternate screen (original behavior). - `never`: Never use alternate screen (inline mode only, preserves scrollback).\n\nUsing alternate screen provides a cleaner fullscreen experience but prevents scrollback in terminal multiplexers like Zellij that follow the xterm spec.",
        validate_default=True,
    )
    animations: bool | None = Field(
        True,
        description="Enable animations (welcome screen, shimmer effects, spinners). Defaults to `true`.",
    )
    keymap: TuiKeymap | None = Field(
        {
            "approval": {
                "approve": None,
                "approve_for_prefix": None,
                "approve_for_session": None,
                "cancel": None,
                "decline": None,
                "deny": None,
                "open_fullscreen": None,
                "open_thread": None,
            },
            "chat": {
                "decrease_reasoning_effort": None,
                "edit_queued_message": None,
                "increase_reasoning_effort": None,
            },
            "composer": {
                "history_search_next": None,
                "history_search_previous": None,
                "queue": None,
                "submit": None,
                "toggle_shortcuts": None,
            },
            "editor": {
                "delete_backward": None,
                "delete_backward_word": None,
                "delete_forward": None,
                "delete_forward_word": None,
                "insert_newline": None,
                "kill_line_end": None,
                "kill_line_start": None,
                "kill_whole_line": None,
                "move_down": None,
                "move_left": None,
                "move_line_end": None,
                "move_line_start": None,
                "move_right": None,
                "move_up": None,
                "move_word_left": None,
                "move_word_right": None,
                "yank": None,
            },
            "global": {
                "clear_terminal": None,
                "copy": None,
                "open_external_editor": None,
                "open_transcript": None,
                "queue": None,
                "submit": None,
                "toggle_fast_mode": None,
                "toggle_raw_output": None,
                "toggle_shortcuts": None,
                "toggle_vim_mode": None,
            },
            "list": {
                "accept": None,
                "cancel": None,
                "move_down": None,
                "move_up": None,
            },
            "pager": {
                "close": None,
                "close_transcript": None,
                "half_page_down": None,
                "half_page_up": None,
                "jump_bottom": None,
                "jump_top": None,
                "page_down": None,
                "page_up": None,
                "scroll_down": None,
                "scroll_up": None,
            },
            "vim_normal": {
                "append_after_cursor": None,
                "append_line_end": None,
                "cancel_operator": None,
                "delete_char": None,
                "delete_to_line_end": None,
                "enter_insert": None,
                "insert_line_start": None,
                "move_down": None,
                "move_left": None,
                "move_line_end": None,
                "move_line_start": None,
                "move_right": None,
                "move_up": None,
                "move_word_backward": None,
                "move_word_end": None,
                "move_word_forward": None,
                "open_line_above": None,
                "open_line_below": None,
                "paste_after": None,
                "start_delete_operator": None,
                "start_yank_operator": None,
                "yank_line": None,
            },
            "vim_operator": {
                "cancel": None,
                "delete_line": None,
                "motion_down": None,
                "motion_left": None,
                "motion_line_end": None,
                "motion_line_start": None,
                "motion_right": None,
                "motion_up": None,
                "motion_word_backward": None,
                "motion_word_end": None,
                "motion_word_forward": None,
                "yank_line": None,
            },
        },
        description="Keybinding overrides for the TUI.\n\nThis supports rebinding selected actions globally and by context. Context bindings take precedence over `global` bindings.",
        validate_default=True,
    )
    model_availability_nux: ModelAvailabilityNuxConfig | None = Field(
        {},
        description="Startup tooltip availability NUX state persisted by the TUI.",
        validate_default=True,
    )
    notification_condition: NotificationCondition | None = Field(
        "unfocused",
        description="Controls whether TUI notifications are delivered only when the terminal is unfocused or regardless of focus. Defaults to `unfocused`.",
        validate_default=True,
    )
    notification_method: NotificationMethod | None = Field(
        "auto",
        description="Notification method to use for terminal notifications. Defaults to `auto`.",
    )
    notifications: Notifications | None = Field(
        True,
        description="Enable desktop notifications from the TUI. Defaults to `true`.",
        validate_default=True,
    )
    raw_output_mode: bool | None = Field(
        False,
        description="Start the TUI in raw scrollback mode for copy-friendly transcript output. Defaults to `false`.",
    )
    session_picker_view: SessionPickerViewMode | None = Field(
        None, description="Preferred layout for resume/fork session picker results."
    )
    show_tooltips: bool | None = Field(
        True,
        description="Show startup tooltips in the TUI welcome screen. Defaults to `true`.",
    )
    status_line: list[str] | None = Field(
        None,
        description="Ordered list of status line item identifiers.\n\nWhen set, the TUI renders the selected items as the status line. When unset, the TUI defaults to: `model-with-reasoning` and `current-dir`.",
    )
    status_line_use_colors: bool | None = Field(
        True,
        description="Color status line items with colors derived from the active syntax theme. Defaults to `true`.",
    )
    terminal_resize_reflow_max_rows: int | None = Field(
        None,
        description="Trim terminal resize-reflow replay to the most recent rendered terminal rows when the transcript exceeds this cap. Omit to use Codex's terminal-specific default. Set to `0` to keep all rendered rows.",
        ge=0,
    )
    terminal_title: list[str] | None = Field(
        None,
        description="Ordered list of terminal title item identifiers.\n\nWhen set, the TUI renders the selected items into the terminal window/tab title. When unset, the TUI defaults to: `activity` and `project`. The `activity` item spins while working and shows an action-required message when blocked on the user.",
    )
    theme: str | None = Field(
        None,
        description="Syntax highlighting theme name (kebab-case).\n\nWhen set, overrides automatic light/dark theme detection. Use `/theme` in the TUI or see `$CODEX_HOME/themes` for custom themes.",
    )
    vim_mode_default: bool | None = Field(
        False,
        description="Start the composer in Vim mode (`Normal`) by default. Defaults to `false`.",
    )


class ConfigToml(BaseModel):
    """
    Base config deserialized from ~/.codex/config.toml.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    agents: AgentsToml | None = Field(
        None, description="Agent-related settings (thread limits, etc.)."
    )
    allow_login_shell: bool | None = Field(
        True,
        description="Whether the model may request a login shell for shell-based tools. Default to `true`\n\nIf `true`, the model may request a login shell (`login = true`), and omitting `login` defaults to using a login shell. If `false`, the model can never use a login shell: `login = true` requests are rejected, and omitting `login` defaults to a non-login shell.",
    )
    analytics: AnalyticsConfigToml | None = Field(
        None,
        description="When `false`, disables analytics across Codex product surfaces in this machine. Defaults to `true`.",
    )
    approval_policy: AskForApproval | None = Field(
        None, description="Default approval policy for executing commands."
    )
    approvals_reviewer: ApprovalsReviewer | None = Field(
        None,
        description="Configures who approval requests are routed to for review once they have been escalated. This does not disable separate safety checks such as ARC.",
    )
    apps: AppsConfigToml | None = Field(None, description="Settings for app-specific controls.")
    audio: RealtimeAudioToml | None = Field(
        None,
        description="Machine-local realtime audio device preferences used by realtime voice.",
    )
    auto_review: AutoReviewToml | None = Field(
        None, description="Optional policy instructions for the guardian auto-reviewer."
    )
    background_terminal_max_timeout: int | None = Field(
        None,
        description="Maximum poll window for background terminal output (`write_stdin`), in milliseconds. Default: `300000` (5 minutes).",
        ge=0,
    )
    chatgpt_base_url: str | None = Field(
        None,
        description="Base URL for requests to ChatGPT (as opposed to the OpenAI API).",
    )
    check_for_update_on_startup: bool | None = Field(
        None,
        description="When `true`, checks for Codex updates on startup and surfaces update prompts. Set to `false` only if your Codex updates are centrally managed. Defaults to `true`.",
    )
    cli_auth_credentials_store: AuthCredentialsStoreMode | None = Field(
        None,
        description="Preferred backend for storing CLI auth credentials. file (default): Use a file in the Codex home directory. keyring: Use an OS-specific keyring service. auto: Use the keyring if available, otherwise use a file.",
    )
    commit_attribution: str | None = Field(
        None,
        description="Optional commit attribution text for commit message co-author trailers. This top-level setting only takes effect when `[features].codex_git_commit` is enabled.\n\nWhen enabled and unset, Codex uses `Codex <noreply@openai.com>`. Set to an empty string to disable automatic commit attribution.",
    )
    compact_prompt: str | None = Field(
        None, description="Compact prompt used for history compaction."
    )
    debug: DebugToml | None = Field(None, description="Debugging and reproducibility settings.")
    default_permissions: str | None = Field(
        None,
        description="Default permissions profile to apply. Names starting with `:` refer to built-in profiles; other names are resolved from the `[permissions]` table.",
    )
    developer_instructions: str | None = Field(
        None,
        description="Developer instructions inserted as a `developer` role message.",
    )
    disable_paste_burst: bool | None = Field(
        None,
        description="When true, disables burst-paste detection for typed input entirely. All characters are inserted as they are received, and no buffering or placeholder replacement will occur for fast keypress bursts.",
    )
    experimental_compact_prompt_file: AbsolutePathBuf | None = None
    experimental_realtime_start_instructions: str | None = Field(
        None,
        description="Experimental / do not use. Replaces the built-in realtime start instructions inserted into developer messages when realtime becomes active.",
    )
    experimental_realtime_ws_backend_prompt: str | None = Field(
        None,
        description="Experimental / do not use. Overrides only the realtime conversation websocket transport instructions (the `Op::RealtimeConversation` `/ws` session.update instructions) without changing normal prompts.",
    )
    experimental_realtime_ws_base_url: str | None = Field(
        None,
        description="Experimental / do not use. Overrides only the realtime conversation websocket transport base URL (the `Op::RealtimeConversation` `/v1/realtime` connection) without changing normal provider HTTP requests.",
    )
    experimental_realtime_ws_model: str | None = Field(
        None,
        description="Experimental / do not use. Selects the realtime websocket model/snapshot used for the `Op::RealtimeConversation` connection.",
    )
    experimental_realtime_ws_startup_context: str | None = Field(
        None,
        description="Experimental / do not use. Replaces the synthesized realtime startup context appended to websocket session instructions. An empty string disables startup context injection entirely.",
    )
    experimental_thread_config_endpoint: str | None = Field(
        None,
        description="Experimental / do not use. When set, app-server fetches thread-scoped config from a remote service at this endpoint.",
    )
    experimental_thread_store: ThreadStoreToml | None = Field(
        None,
        description="Experimental / do not use. Selects the thread store implementation.",
    )
    experimental_use_freeform_apply_patch: bool | None = None
    experimental_use_unified_exec_tool: bool | None = None
    features: Features | None = Field(
        None,
        description="Centralized feature flags (new). Prefer this over individual toggles.",
    )
    feedback: FeedbackConfigToml | None = Field(
        None,
        description="When `false`, disables feedback collection across Codex product surfaces. Defaults to `true`.",
    )
    file_opener: UriBasedFileOpener | None = Field(
        None,
        description="Optional URI-based file opener. If set, citations to files in the model output will be hyperlinked using the specified URI scheme.",
    )
    forced_chatgpt_workspace_id: str | None = Field(
        None,
        description="When set, restricts ChatGPT login to a specific workspace identifier.",
    )
    forced_login_method: ForcedLoginMethod | None = Field(
        None, description="When set, restricts the login mechanism users may use."
    )
    ghost_snapshot: GhostSnapshotToml | None = Field(
        None,
        description="Compatibility-only settings retained so legacy `ghost_snapshot` config still loads.",
    )
    hide_agent_reasoning: bool | None = Field(
        False,
        description="When set to `true`, `AgentReasoning` events will be hidden from the UI/output. Defaults to `false`.",
    )
    history: History | None = Field(
        {"max_bytes": None, "persistence": "save-all"},
        description="Settings that govern if and what will be written to `~/.codex/history.jsonl`.",
        validate_default=True,
    )
    hooks: HooksToml | None = Field(
        None,
        description="Lifecycle hooks configured inline in TOML plus user-level overrides.",
    )
    include_apps_instructions: bool | None = Field(
        None, description="Whether to inject the `<apps_instructions>` developer block."
    )
    include_environment_context: bool | None = Field(
        None, description="Whether to inject the `<environment_context>` user block."
    )
    include_permissions_instructions: bool | None = Field(
        None,
        description="Whether to inject the `<permissions instructions>` developer block.",
    )
    instructions: str | None = Field(None, description="System instructions.")
    log_dir: AbsolutePathBuf | None = Field(
        None,
        description="Directory where Codex writes log files, for example `codex-tui.log`. Defaults to `$CODEX_HOME/log`.",
    )
    marketplaces: dict[str, MarketplaceConfig] | None = Field(
        {},
        description="User-level marketplace entries keyed by marketplace name.",
        validate_default=True,
    )
    mcp_oauth_callback_port: int | None = Field(
        None,
        description="Optional fixed port for the local HTTP callback server used during MCP OAuth login. When unset, Codex will bind to an ephemeral port chosen by the OS.",
        ge=0,
    )
    mcp_oauth_callback_url: str | None = Field(
        None,
        description="Optional redirect URI to use during MCP OAuth login. When set, this URI is used in the OAuth authorization request instead of the local listener address. The local callback listener still binds to 127.0.0.1 (using `mcp_oauth_callback_port` when provided).",
    )
    mcp_oauth_credentials_store: OAuthCredentialsStoreMode | None = Field(
        None,
        description="Preferred backend for storing MCP OAuth credentials. keyring: Use an OS-specific keyring service. https://github.com/openai/codex/blob/main/codex-rs/rmcp-client/src/oauth.rs#L2 file: Use a file in the Codex home directory. auto (default): Use the OS-specific keyring service if available, otherwise use a file.",
    )
    mcp_servers: dict[str, RawMcpServerConfig] | None = Field(
        {},
        description="Definition for MCP servers that Codex can reach out to for tool calls.",
        validate_default=True,
    )
    memories: MemoriesToml | None = Field(None, description="Memories subsystem settings.")
    model: str | None = Field(None, description="Optional override of model selection.")
    model_auto_compact_token_limit: int | None = Field(
        None,
        description="Token usage threshold triggering auto-compaction of conversation history.",
    )
    model_catalog_json: AbsolutePathBuf | None = Field(
        None,
        description="Optional path to a JSON model catalog (applied on startup only). Per-thread `config` overrides are accepted but do not reapply this (no-ops).",
    )
    model_context_window: int | None = Field(
        None, description="Size of the context window for the model, in tokens."
    )
    model_instructions_file: AbsolutePathBuf | None = Field(
        None,
        description="Optional path to a file containing model instructions that will override the built-in instructions for the selected model. Users are STRONGLY DISCOURAGED from using this field, as deviating from the instructions sanctioned by Codex will likely degrade model performance.",
    )
    model_provider: str | None = Field(
        None, description="Provider to use from the model_providers map."
    )
    model_providers: dict[str, ModelProviderInfo] | None = Field(
        {},
        description="User-defined provider entries that extend the built-in list. Built-in IDs cannot be overridden.",
        validate_default=True,
    )
    model_reasoning_effort: ReasoningEffort | None = None
    model_reasoning_summary: ReasoningSummary | None = None
    model_supports_reasoning_summaries: bool | None = Field(
        None,
        description="Override to force-enable reasoning summaries for the configured model.",
    )
    model_verbosity: Verbosity | None = Field(
        None,
        description="Optional verbosity control for GPT-5 models (Responses API `text.verbosity`).",
    )
    notice: Notice | None = Field(
        None,
        description="Collection of in-product notices (different from notifications) See [`crate::types::Notice`] for more details",
    )
    notify: list[str] | None = Field(
        None,
        description="Optional external command to spawn for end-user notifications.",
    )
    openai_base_url: str | None = Field(
        None, description="Base URL override for the built-in `openai` model provider."
    )
    oss_provider: str | None = Field(
        None,
        description='Preferred OSS provider for local models, e.g. "lmstudio" or "ollama".',
    )
    otel: OtelConfigToml | None = Field(None, description="OTEL configuration.")
    permissions: PermissionsToml | None = Field(None, description="Named permissions profiles.")
    personality: Personality | None = Field(
        None, description="Optionally specify a personality for the model"
    )
    plan_mode_reasoning_effort: ReasoningEffort | None = None
    plugins: dict[str, PluginConfig] | None = Field(
        {},
        description="User-level plugin config entries keyed by plugin name.",
        validate_default=True,
    )
    profile: str | None = Field(None, description="Profile to use from the `profiles` map.")
    profiles: dict[str, ConfigProfile] | None = Field(
        {},
        description="Named profiles to facilitate switching between different configurations.",
        validate_default=True,
    )
    project_doc_fallback_filenames: list[str] | None = Field(
        [],
        description="Ordered list of fallback filenames to look for when AGENTS.md is missing.",
    )
    project_doc_max_bytes: int | None = Field(
        32768,
        description="Maximum number of bytes to include from an AGENTS.md project doc file.",
        ge=0,
    )
    project_root_markers: list[str] | None = Field(
        None,
        description='Markers used to detect the project root when searching parent directories for `.codex` folders. Defaults to [".git"] when unset.',
    )
    projects: dict[str, Any] | None = None
    realtime: RealtimeToml | None = Field(
        None,
        description="Experimental / do not use. Realtime websocket session selection. `version` controls v1/v2 and `type` controls conversational/transcription.",
    )
    review_model: str | None = Field(
        None, description="Review model override used by the `/review` feature."
    )
    sandbox_mode: SandboxMode | None = Field(None, description="Sandbox mode to use.")
    sandbox_workspace_write: SandboxWorkspaceWrite | None = Field(
        None,
        description="Sandbox configuration to apply if `sandbox` is `WorkspaceWrite`.",
    )
    service_tier: str | None = Field(
        None,
        description="Optional explicit service tier request id for new turns (for example `priority` or `flex`; legacy `fast` also works).",
    )
    shell_environment_policy: ShellEnvironmentPolicyToml | None = Field(
        {
            "exclude": None,
            "experimental_use_profile": None,
            "ignore_default_excludes": None,
            "include_only": None,
            "inherit": None,
            "set": None,
        },
        validate_default=True,
    )
    show_raw_agent_reasoning: bool | None = Field(
        None,
        description="When set to `true`, `AgentReasoningRawContentEvent` events will be shown in the UI/output. Defaults to `false`.",
    )
    skills: SkillsConfig | None = Field(
        None, description="User-level skill config entries keyed by SKILL.md path."
    )
    sqlite_home: AbsolutePathBuf | None = Field(
        None,
        description="Directory where Codex stores the SQLite state DB. Defaults to `$CODEX_SQLITE_HOME` when set. Otherwise uses `$CODEX_HOME`.",
    )
    suppress_unstable_features_warning: bool | None = Field(
        None,
        description="Suppress warnings about unstable (under development) features.",
    )
    tool_output_token_limit: int | None = Field(
        None,
        description="Token budget applied when storing tool/function outputs in the context manager.",
        ge=0,
    )
    tool_suggest: ToolSuggestConfig | None = Field(
        None,
        description="Additional discoverable tools that can be suggested for installation.",
    )
    tools: ToolsToml | None = Field(None, description="Nested tools section for feature toggles")
    tui: Tui | None = Field(
        None, description="Collection of settings that are specific to the TUI."
    )
    web_search: WebSearchMode | None = Field(
        None,
        description="Controls the web search tool mode: disabled, cached, or live.",
    )
    windows: WindowsToml | None = Field(None, description="Windows-specific configuration.")
    windows_wsl_setup_acknowledged: bool | None = Field(
        None,
        description="Tracks whether the Windows onboarding screen has been acknowledged.",
    )
    zsh_path: AbsolutePathBuf | None = Field(
        None,
        description="Optional absolute path to patched zsh used by zsh-exec-bridge-backed shell execution.",
    )
